spring:
  application:
    name: discovery-ha
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456

---
server:
  port: 8761


spring:
  profiles: peer1

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    appname: discovery-ha
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health

  client:
    service-url:
      defaultZone: http://root:123456@peer2:8762/eureka,http://root:123456@peer3:8763/eureka
    register-with-eureka: true
    fetch-registry: true

---
server:
  port: 8762

spring:
  profiles: peer2

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    appname: discovery-ha
  client:
    service-url:
      defaultZone: http://root:123456@peer1:8761/eureka,http://root:123456@peer3:8763/eureka
    register-with-eureka: true
    fetch-registry: true

---
server:
  port: 8763

spring:
  profiles: peer3

eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
    appname: discovery-ha
  client:
    service-url:
      defaultZone: http://root:123456@peer1:8761/eureka,http://root:123456@peer2:8762/eureka
    register-with-eureka: true
    fetch-registry: true
